// Speaker and Faculty Photo Registry
// Synchronized with ISOT 2026 Brochure V23-1 & Official Faculty Directory

export const SPEAKER_IMAGE_MAP: Record<string, string> = {
  'Abhijat Sheth': '/speaker-photos/abhijat-sheth.png',
  'Adrienne Seitz': '/speaker-photos/adrienne-seitz.png',
  'Ajay Sharma': '/speaker-photos/ajay-sharma.png',
  'Akash Shukla': '/speaker-photos/akash-shukla.png',
  'Allan Massie': '/speaker-photos/allan-massie.png',
  'Amit Gupta': '/speaker-photos/amit-gupta.png',
  'Aneesh Srivastava': '/speaker-photos/aneesh-srivastava.png',
  'Anshuman Saha': '/speaker-photos/anshuman-saha.png',
  'Anup Barman': '/speaker-photos/anup-barman.png',
  'Anurag Gupta': '/speaker-photos/anurag-gupta.png',
  'Arpita Ray Chaudhury': '/speaker-photos/arpita-ray-chaudhury.png',
  'Ashish Shah': '/speaker-photos/ashish-shah.png',
  'Atul Goel': '/speaker-photos/atul-goel.png',
  'Avnish Seth': '/speaker-photos/avnish-seth.png',
  'Awadhesh Kumar Yadav': '/speaker-photos/awadhesh-kumar-yadav.png',
  'Debasis Das': '/speaker-photos/debasis-das.png',
  'Deepesh Kenwar': '/speaker-photos/deepesh-kenwar.png',
  'Dhananjai Agarwal': '/speaker-photos/dhananjai-agrawal.png',
  'Dhananjai Agrawal': '/speaker-photos/dhananjai-agrawal.png',
  'Dhananjaya K L': '/speaker-photos/dhananjaya-k-l.png',
  'Dhannanjay Agarwal': '/speaker-photos/dhananjai-agrawal.png',
  'Dilip Deshmukh': '/speaker-photos/dilip-deshmukh.png',
  'Dolly Daniel': '/speaker-photos/dolly-daniel.png',
  'Dr. Abhijat Sheth': '/speaker-photos/abhijat-sheth.png',
  'Dr. Adrienne Seitz': '/speaker-photos/adrienne-seitz.png',
  'Dr. Ajay Sharma': '/speaker-photos/ajay-sharma.png',
  'Dr. Akash Shukla': '/speaker-photos/akash-shukla.png',
  'Dr. Allan Massie': '/speaker-photos/allan-massie.png',
  'Dr. Amit Gupta': '/speaker-photos/amit-gupta.png',
  'Dr. Aneesh Srivastava': '/speaker-photos/aneesh-srivastava.png',
  'Dr. Anshuman Saha': '/speaker-photos/anshuman-saha.png',
  'Dr. Anup Barman': '/speaker-photos/anup-barman.png',
  'Dr. Anurag Gupta': '/speaker-photos/anurag-gupta.png',
  'Dr. Arpita Ray Chaudhury': '/speaker-photos/arpita-ray-chaudhury.png',
  'Dr. Ashish Shah': '/speaker-photos/ashish-shah.png',
  'Dr. Atul Goel': '/speaker-photos/atul-goel.png',
  'Dr. Avnish Seth': '/speaker-photos/avnish-seth.png',
  'Dr. Awadhesh Kumar Yadav': '/speaker-photos/awadhesh-kumar-yadav.png',
  'Dr. Debasis Das': '/speaker-photos/debasis-das.png',
  'Dr. Deepesh Kenwar': '/speaker-photos/deepesh-kenwar.png',
  'Dr. Dhananjai Agarwal': '/speaker-photos/dhananjai-agrawal.png',
  'Dr. Dhananjai Agrawal': '/speaker-photos/dhananjai-agrawal.png',
  'Dr. Dhananjaya K L': '/speaker-photos/dhananjaya-k-l.png',
  'Dr. Dhannanjay Agarwal': '/speaker-photos/dhananjai-agrawal.png',
  'Dr. Dilip Deshmukh': '/speaker-photos/dilip-deshmukh.png',
  'Dr. Dolly Daniel': '/speaker-photos/dolly-daniel.png',
  'Dr. Edwin Fernando': '/speaker-photos/edwin-fernando.png',
  'Dr. Feroz Aziz': '/speaker-photos/feroz-aziz.png',
  'Dr. Geetesh MS': '/speaker-photos/geetesh-ms.png',
  'Dr. Georgi Abraham': '/speaker-photos/georgi-abraham.png',
  'Dr. Gireesh MS': '/speaker-photos/geetesh-ms.png',
  'Dr. Gopala Krishna Gokhale': '/speaker-photos/gopala-krishna-gokhale.png',
  'Dr. Gopaluni Seerapani': '/speaker-photos/gopaluni-sirapani.png',
  'Dr. Gopaluni Sirapani': '/speaker-photos/gopaluni-sirapani.png',
  'Dr. Hari Shankar Meshram': '/speaker-photos/hari-shankar-meshram.png',
  'Dr. Jasmeet Kaur': '/speaker-photos/jasmeet-kaur.png',
  'Dr. Jayesh Sachde': '/speaker-photos/jayesh-sachde.png',
  'Dr. Jeyakumar Meyyappan': '/speaker-photos/jeyakumar-meyyappan.png',
  'Dr. Jithu Kurian': '/speaker-photos/jithu-kurian.png',
  'Dr. Khushboo Saxena': '/speaker-photos/khushboo-saxena.png',
  'Dr. Kishor Wani': '/speaker-photos/kishor-wani.png',
  'Dr. Koushik Amancharla': '/speaker-photos/koushik-amancharla.png',
  'Dr. Krishna V Patil': '/speaker-photos/krishna-v-patil.png',
  'Dr. Mahesh V': '/speaker-photos/mahesh-vankalakunti.png',
  'Dr. Mahesh Vankalakunti': '/speaker-photos/mahesh-vankalakunti.png',
  'Dr. Mahesha V': '/speaker-photos/mahesh-vankalakunti.png',
  'Dr. Mamidi Neeraja': '/speaker-photos/mamidi-neeraja.png',
  'Dr. Manish Balwani': '/speaker-photos/manish-balwani.png',
  'Dr. Manish Jain': '/speaker-photos/manish-jain.png',
  'Dr. Manish R Balwani': '/speaker-photos/manish-balwani.png',
  'Dr. Manish Shrigiriwa': '/speaker-photos/manish-singhshikha.png',
  'Dr. Manish Singhshikha': '/speaker-photos/manish-singhshikha.png',
  'Dr. Marcello Cantarovich': '/speaker-photos/marcello-cantarovich.png',
  'Dr. Maria Paula Gomez': '/speaker-photos/maria-paula-gomez.png',
  'Dr. Mehul Shah': '/speaker-photos/mehul-shah.png',
  'Dr. Mohamed Rela': '/speaker-photos/mohamed-rela.png',
  'Dr. N Gopalakrishnan': '/speaker-photos/natarajan-gopalakrishnan.png',
  'Dr. Narayan Prasad': '/speaker-photos/narayan-prasad.png',
  'Dr. Natarajan Gopalakrishnan': '/speaker-photos/natarajan-gopalakrishnan.png',
  'Dr. Neelam Mohan': '/speaker-photos/neelam-mohan.png',
  'Dr. Nilesh Mandlewal': '/speaker-photos/nilesh-mandlewal.png',
  'Dr. Pranab Modi': '/speaker-photos/pranab-modi.png',
  'Dr. Pranav Modi': '/speaker-photos/pranab-modi.png',
  'Dr. Pratik Das': '/speaker-photos/pratik-das.png',
  'Dr. RP Mathur': '/speaker-photos/rp-mathur.png',
  'Dr. Radhika Krishna Patil': '/speaker-photos/krishna-v-patil.png',
  'Dr. Rahul Pandit': '/speaker-photos/rahul-pandit.png',
  'Dr. Raj Kanwar Yadav': '/speaker-photos/raj-kumar-yadav.png',
  'Dr. Raj Kumar Yadav': '/speaker-photos/raj-kumar-yadav.png',
  'Dr. Rajani M': '/speaker-photos/rajani-m.png',
  'Dr. Rakesh Joshi': '/speaker-photos/rakesh-joshi.png',
  'Dr. Ravi Mohanka': '/speaker-photos/ravi-mohanka.png',
  'Dr. Ritu Agarwal': '/speaker-photos/ritu-agarwal.png',
  'Dr. Rushi Deshpande': '/speaker-photos/rushi-deshpande.png',
  'Dr. S Sakthi Selva Kumar': '/speaker-photos/s-sakthi-selva-kumar.png',
  'Dr. Sakthi Selvakumar': '/speaker-photos/s-sakthi-selva-kumar.png',
  'Dr. Sandeep Attawar': '/speaker-photos/sandeep-attawar.png',
  'Dr. Sanjay Kolte': '/speaker-photos/sanjay-kolte.png',
  'Dr. Sanjay Kumar Agarwal': '/speaker-photos/sanjay-kumar-agarwal.png',
  'Dr. Sanjay Nagral': '/speaker-photos/sanjay-nagral.png',
  'Dr. Santosh Varughese': '/speaker-photos/santosh-varughese.png',
  'Dr. Sarbpreet Singh': '/speaker-photos/sarbpreet-singh.png',
  'Dr. Shalini Garg': '/speaker-photos/shalini-garg.png',
  'Dr. Sharadalekha Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Dr. Shiny Pradhan': '/speaker-photos/shiny-suman-pradhan.png',
  'Dr. Shiny Suman Pradhan': '/speaker-photos/shiny-suman-pradhan.png',
  'Dr. Sidharth Sethi': '/speaker-photos/sidharth-sethi.png',
  'Dr. Sourabh Sharma': '/speaker-photos/sourabh-sharma.png',
  'Dr. Sree Bhushan Raju': '/speaker-photos/sree-bhushan-raju.png',
  'Dr. Subramania Iyer': '/speaker-photos/subramania-iyer.png',
  'Dr. Sukanto Das': '/speaker-photos/sukanto-kishore-das.png',
  'Dr. Sukanto Kishore Das': '/speaker-photos/sukanto-kishore-das.png',
  'Dr. Sunil Shroff': '/speaker-photos/sunil-shroff.png',
  'Dr. Sunil Vasudevan': '/speaker-photos/sunil-vasudevan.png',
  'Dr. Swarnalata Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Dr. Swarnalatha Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Dr. Umapati Hegde': '/speaker-photos/umapati-hegde.png',
  'Dr. V.K. Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Dr. VK Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Dr. Vatsala Trivedi': '/speaker-photos/vatsala-trivedi.png',
  'Dr. Vinant Bhargava': '/speaker-photos/vinant-bhargava.png',
  'Dr. Vinod Kumar Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Dr. Vivek Kute': '/speaker-photos/vivek-kute.png',
  'Dr. Yogaram Jabble': '/speaker-photos/yogaram-jabble.png',
  'Edwin Fernando': '/speaker-photos/edwin-fernando.png',
  'Feroz Aziz': '/speaker-photos/feroz-aziz.png',
  'Geetesh MS': '/speaker-photos/geetesh-ms.png',
  'Georgi Abraham': '/speaker-photos/georgi-abraham.png',
  'Gireesh MS': '/speaker-photos/geetesh-ms.png',
  'Gopala Krishna Gokhale': '/speaker-photos/gopala-krishna-gokhale.png',
  'Gopaluni Seerapani': '/speaker-photos/gopaluni-sirapani.png',
  'Gopaluni Sirapani': '/speaker-photos/gopaluni-sirapani.png',
  'Hari Shankar Meshram': '/speaker-photos/hari-shankar-meshram.png',
  'Jasmeet Kaur': '/speaker-photos/jasmeet-kaur.png',
  'Jayesh Sachde': '/speaker-photos/jayesh-sachde.png',
  'Jeyakumar Meyyappan': '/speaker-photos/jeyakumar-meyyappan.png',
  'Jithu Kurian': '/speaker-photos/jithu-kurian.png',
  'Khushboo Saxena': '/speaker-photos/khushboo-saxena.png',
  'Kishor Wani': '/speaker-photos/kishor-wani.png',
  'Koushik Amancharla': '/speaker-photos/koushik-amancharla.png',
  'Krishna V Patil': '/speaker-photos/krishna-v-patil.png',
  'Mahesh V': '/speaker-photos/mahesh-vankalakunti.png',
  'Mahesh Vankalakunti': '/speaker-photos/mahesh-vankalakunti.png',
  'Mahesha V': '/speaker-photos/mahesh-vankalakunti.png',
  'Mamidi Neeraja': '/speaker-photos/mamidi-neeraja.png',
  'Manish Balwani': '/speaker-photos/manish-balwani.png',
  'Manish Jain': '/speaker-photos/manish-jain.png',
  'Manish R Balwani': '/speaker-photos/manish-balwani.png',
  'Manish Shrigiriwa': '/speaker-photos/manish-singhshikha.png',
  'Manish Singhshikha': '/speaker-photos/manish-singhshikha.png',
  'Marcello Cantarovich': '/speaker-photos/marcello-cantarovich.png',
  'Maria Paula Gomez': '/speaker-photos/maria-paula-gomez.png',
  'Mehul Shah': '/speaker-photos/mehul-shah.png',
  'Mohamed Rela': '/speaker-photos/mohamed-rela.png',
  'N Gopalakrishnan': '/speaker-photos/natarajan-gopalakrishnan.png',
  'Narayan Prasad': '/speaker-photos/narayan-prasad.png',
  'Natarajan Gopalakrishnan': '/speaker-photos/natarajan-gopalakrishnan.png',
  'Neelam Mohan': '/speaker-photos/neelam-mohan.png',
  'Nilesh Mandlewal': '/speaker-photos/nilesh-mandlewal.png',
  'Pranab Modi': '/speaker-photos/pranab-modi.png',
  'Pranav Modi': '/speaker-photos/pranab-modi.png',
  'Pratik Das': '/speaker-photos/pratik-das.png',
  'Prof. Abhijat Sheth': '/speaker-photos/abhijat-sheth.png',
  'Prof. Adrienne Seitz': '/speaker-photos/adrienne-seitz.png',
  'Prof. Ajay Sharma': '/speaker-photos/ajay-sharma.png',
  'Prof. Akash Shukla': '/speaker-photos/akash-shukla.png',
  'Prof. Allan Massie': '/speaker-photos/allan-massie.png',
  'Prof. Amit Gupta': '/speaker-photos/amit-gupta.png',
  'Prof. Aneesh Srivastava': '/speaker-photos/aneesh-srivastava.png',
  'Prof. Anshuman Saha': '/speaker-photos/anshuman-saha.png',
  'Prof. Anup Barman': '/speaker-photos/anup-barman.png',
  'Prof. Anurag Gupta': '/speaker-photos/anurag-gupta.png',
  'Prof. Arpita Ray Chaudhury': '/speaker-photos/arpita-ray-chaudhury.png',
  'Prof. Ashish Shah': '/speaker-photos/ashish-shah.png',
  'Prof. Atul Goel': '/speaker-photos/atul-goel.png',
  'Prof. Avnish Seth': '/speaker-photos/avnish-seth.png',
  'Prof. Awadhesh Kumar Yadav': '/speaker-photos/awadhesh-kumar-yadav.png',
  'Prof. Debasis Das': '/speaker-photos/debasis-das.png',
  'Prof. Deepesh Kenwar': '/speaker-photos/deepesh-kenwar.png',
  'Prof. Dhananjai Agarwal': '/speaker-photos/dhananjai-agrawal.png',
  'Prof. Dhananjai Agrawal': '/speaker-photos/dhananjai-agrawal.png',
  'Prof. Dhananjaya K L': '/speaker-photos/dhananjaya-k-l.png',
  'Prof. Dhannanjay Agarwal': '/speaker-photos/dhananjai-agrawal.png',
  'Prof. Dilip Deshmukh': '/speaker-photos/dilip-deshmukh.png',
  'Prof. Dolly Daniel': '/speaker-photos/dolly-daniel.png',
  'Prof. Edwin Fernando': '/speaker-photos/edwin-fernando.png',
  'Prof. Feroz Aziz': '/speaker-photos/feroz-aziz.png',
  'Prof. Geetesh MS': '/speaker-photos/geetesh-ms.png',
  'Prof. Georgi Abraham': '/speaker-photos/georgi-abraham.png',
  'Prof. Gireesh MS': '/speaker-photos/geetesh-ms.png',
  'Prof. Gopala Krishna Gokhale': '/speaker-photos/gopala-krishna-gokhale.png',
  'Prof. Gopaluni Seerapani': '/speaker-photos/gopaluni-sirapani.png',
  'Prof. Gopaluni Sirapani': '/speaker-photos/gopaluni-sirapani.png',
  'Prof. Hari Shankar Meshram': '/speaker-photos/hari-shankar-meshram.png',
  'Prof. Jasmeet Kaur': '/speaker-photos/jasmeet-kaur.png',
  'Prof. Jayesh Sachde': '/speaker-photos/jayesh-sachde.png',
  'Prof. Jeyakumar Meyyappan': '/speaker-photos/jeyakumar-meyyappan.png',
  'Prof. Jithu Kurian': '/speaker-photos/jithu-kurian.png',
  'Prof. Khushboo Saxena': '/speaker-photos/khushboo-saxena.png',
  'Prof. Kishor Wani': '/speaker-photos/kishor-wani.png',
  'Prof. Koushik Amancharla': '/speaker-photos/koushik-amancharla.png',
  'Prof. Krishna V Patil': '/speaker-photos/krishna-v-patil.png',
  'Prof. Mahesh V': '/speaker-photos/mahesh-vankalakunti.png',
  'Prof. Mahesh Vankalakunti': '/speaker-photos/mahesh-vankalakunti.png',
  'Prof. Mahesha V': '/speaker-photos/mahesh-vankalakunti.png',
  'Prof. Mamidi Neeraja': '/speaker-photos/mamidi-neeraja.png',
  'Prof. Manish Balwani': '/speaker-photos/manish-balwani.png',
  'Prof. Manish Jain': '/speaker-photos/manish-jain.png',
  'Prof. Manish R Balwani': '/speaker-photos/manish-balwani.png',
  'Prof. Manish Shrigiriwa': '/speaker-photos/manish-singhshikha.png',
  'Prof. Manish Singhshikha': '/speaker-photos/manish-singhshikha.png',
  'Prof. Marcello Cantarovich': '/speaker-photos/marcello-cantarovich.png',
  'Prof. Maria Paula Gomez': '/speaker-photos/maria-paula-gomez.png',
  'Prof. Mehul Shah': '/speaker-photos/mehul-shah.png',
  'Prof. Mohamed Rela': '/speaker-photos/mohamed-rela.png',
  'Prof. N Gopalakrishnan': '/speaker-photos/natarajan-gopalakrishnan.png',
  'Prof. Narayan Prasad': '/speaker-photos/narayan-prasad.png',
  'Prof. Natarajan Gopalakrishnan': '/speaker-photos/natarajan-gopalakrishnan.png',
  'Prof. Neelam Mohan': '/speaker-photos/neelam-mohan.png',
  'Prof. Nilesh Mandlewal': '/speaker-photos/nilesh-mandlewal.png',
  'Prof. Pranab Modi': '/speaker-photos/pranab-modi.png',
  'Prof. Pranav Modi': '/speaker-photos/pranab-modi.png',
  'Prof. Pratik Das': '/speaker-photos/pratik-das.png',
  'Prof. RP Mathur': '/speaker-photos/rp-mathur.png',
  'Prof. Radhika Krishna Patil': '/speaker-photos/krishna-v-patil.png',
  'Prof. Rahul Pandit': '/speaker-photos/rahul-pandit.png',
  'Prof. Raj Kanwar Yadav': '/speaker-photos/raj-kumar-yadav.png',
  'Prof. Raj Kumar Yadav': '/speaker-photos/raj-kumar-yadav.png',
  'Prof. Rajani M': '/speaker-photos/rajani-m.png',
  'Prof. Rakesh Joshi': '/speaker-photos/rakesh-joshi.png',
  'Prof. Ravi Mohanka': '/speaker-photos/ravi-mohanka.png',
  'Prof. Ritu Agarwal': '/speaker-photos/ritu-agarwal.png',
  'Prof. Rushi Deshpande': '/speaker-photos/rushi-deshpande.png',
  'Prof. S Sakthi Selva Kumar': '/speaker-photos/s-sakthi-selva-kumar.png',
  'Prof. Sakthi Selvakumar': '/speaker-photos/s-sakthi-selva-kumar.png',
  'Prof. Sandeep Attawar': '/speaker-photos/sandeep-attawar.png',
  'Prof. Sanjay Kolte': '/speaker-photos/sanjay-kolte.png',
  'Prof. Sanjay Kumar Agarwal': '/speaker-photos/sanjay-kumar-agarwal.png',
  'Prof. Sanjay Nagral': '/speaker-photos/sanjay-nagral.png',
  'Prof. Santosh Varughese': '/speaker-photos/santosh-varughese.png',
  'Prof. Sarbpreet Singh': '/speaker-photos/sarbpreet-singh.png',
  'Prof. Shalini Garg': '/speaker-photos/shalini-garg.png',
  'Prof. Sharadalekha Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Prof. Shiny Pradhan': '/speaker-photos/shiny-suman-pradhan.png',
  'Prof. Shiny Suman Pradhan': '/speaker-photos/shiny-suman-pradhan.png',
  'Prof. Sidharth Sethi': '/speaker-photos/sidharth-sethi.png',
  'Prof. Sourabh Sharma': '/speaker-photos/sourabh-sharma.png',
  'Prof. Sree Bhushan Raju': '/speaker-photos/sree-bhushan-raju.png',
  'Prof. Subramania Iyer': '/speaker-photos/subramania-iyer.png',
  'Prof. Sukanto Das': '/speaker-photos/sukanto-kishore-das.png',
  'Prof. Sukanto Kishore Das': '/speaker-photos/sukanto-kishore-das.png',
  'Prof. Sunil Shroff': '/speaker-photos/sunil-shroff.png',
  'Prof. Sunil Vasudevan': '/speaker-photos/sunil-vasudevan.png',
  'Prof. Swarnalata Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Prof. Swarnalatha Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Prof. Umapati Hegde': '/speaker-photos/umapati-hegde.png',
  'Prof. V.K. Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Prof. VK Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Prof. Vatsala Trivedi': '/speaker-photos/vatsala-trivedi.png',
  'Prof. Vinant Bhargava': '/speaker-photos/vinant-bhargava.png',
  'Prof. Vinod Kumar Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Prof. Vivek Kute': '/speaker-photos/vivek-kute.png',
  'Prof. Yogaram Jabble': '/speaker-photos/yogaram-jabble.png',
  'RP Mathur': '/speaker-photos/rp-mathur.png',
  'Radhika Krishna Patil': '/speaker-photos/krishna-v-patil.png',
  'Rahul Pandit': '/speaker-photos/rahul-pandit.png',
  'Raj Kanwar Yadav': '/speaker-photos/raj-kumar-yadav.png',
  'Raj Kumar Yadav': '/speaker-photos/raj-kumar-yadav.png',
  'Rajani M': '/speaker-photos/rajani-m.png',
  'Rakesh Joshi': '/speaker-photos/rakesh-joshi.png',
  'Ravi Mohanka': '/speaker-photos/ravi-mohanka.png',
  'Ritu Agarwal': '/speaker-photos/ritu-agarwal.png',
  'Rushi Deshpande': '/speaker-photos/rushi-deshpande.png',
  'S Sakthi Selva Kumar': '/speaker-photos/s-sakthi-selva-kumar.png',
  'Sakthi Selvakumar': '/speaker-photos/s-sakthi-selva-kumar.png',
  'Sandeep Attawar': '/speaker-photos/sandeep-attawar.png',
  'Sanjay Kolte': '/speaker-photos/sanjay-kolte.png',
  'Sanjay Kumar Agarwal': '/speaker-photos/sanjay-kumar-agarwal.png',
  'Sanjay Nagral': '/speaker-photos/sanjay-nagral.png',
  'Santosh Varughese': '/speaker-photos/santosh-varughese.png',
  'Sarbpreet Singh': '/speaker-photos/sarbpreet-singh.png',
  'Shalini Garg': '/speaker-photos/shalini-garg.png',
  'Sharadalekha Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Shiny Pradhan': '/speaker-photos/shiny-suman-pradhan.png',
  'Shiny Suman Pradhan': '/speaker-photos/shiny-suman-pradhan.png',
  'Sidharth Sethi': '/speaker-photos/sidharth-sethi.png',
  'Sourabh Sharma': '/speaker-photos/sourabh-sharma.png',
  'Sree Bhushan Raju': '/speaker-photos/sree-bhushan-raju.png',
  'Sreebhushan Raju': '/speaker-photos/sree-bhushan-raju.png',
  'Dr Sreebhushan Raju': '/speaker-photos/sree-bhushan-raju.png',
  'Dr. Sreebhushan Raju': '/speaker-photos/sree-bhushan-raju.png',
  'Subramania Iyer': '/speaker-photos/subramania-iyer.png',
  'Sukanto Das': '/speaker-photos/sukanto-kishore-das.png',
  'Sukanto Kishore Das': '/speaker-photos/sukanto-kishore-das.png',
  'Sunil Shroff': '/speaker-photos/sunil-shroff.png',
  'Sunil Vasudevan': '/speaker-photos/sunil-vasudevan.png',
  'Swarnalata Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Swarnalatha Guditi': '/speaker-photos/sharadalekha-guditi.png',
  'Umapati Hegde': '/speaker-photos/umapati-hegde.png',
  'V.K. Paul': '/speaker-photos/vinod-kumar-paul.png',
  'VK Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Vatsala Trivedi': '/speaker-photos/vatsala-trivedi.png',
  'Vinant Bhargava': '/speaker-photos/vinant-bhargava.png',
  'Vinod Kumar Paul': '/speaker-photos/vinod-kumar-paul.png',
  'Vivek Kute': '/speaker-photos/vivek-kute.png',
  'Yogaram Jabble': '/speaker-photos/yogaram-jabble.png',
};

/**
 * Normalizes a speaker name for lookup in the photo map
 */
export function normalizeSpeakerName(name: string): string {
  if (!name) return '';
  return name
    .trim()
    .replace(/^(Dr\.?|Prof\.?|Padma Shri|Padmashri|Padma Bhushan)\s+/i, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Returns the photo URL for a speaker name if available.
 * Checks dynamic uploaded photos first, then static registry.
 */
export function getSpeakerPhoto(
  name: string,
  dynamicPhotos?: Record<string, string>
): string | null {
  if (!name) return null;
  const trimmed = name.trim();
  const normalized = normalizeSpeakerName(trimmed);

  // 1. Dynamic uploaded photos from R2 / D1
  if (dynamicPhotos) {
    const slug = normalized.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    if (dynamicPhotos[slug]) return dynamicPhotos[slug];
    if (dynamicPhotos[trimmed]) return dynamicPhotos[trimmed];
    if (dynamicPhotos[normalized]) return dynamicPhotos[normalized];
  }

  // 2. Exact match in static map
  if (SPEAKER_IMAGE_MAP[trimmed]) {
    return SPEAKER_IMAGE_MAP[trimmed];
  }

  // 3. Normalized match
  if (SPEAKER_IMAGE_MAP[normalized]) {
    return SPEAKER_IMAGE_MAP[normalized];
  }

  // 4. Case-insensitive lookup
  const lowerTrimmed = trimmed.toLowerCase();
  const lowerNormalized = normalized.toLowerCase();
  for (const [key, val] of Object.entries(SPEAKER_IMAGE_MAP)) {
    const kLower = key.toLowerCase();
    if (kLower === lowerTrimmed || kLower === lowerNormalized) {
      return val;
    }
  }

  return null;
}
